apiVersion: apps/v1
kind: Deployment
# Định nghĩa một Kubernetes Deployment để quản lý các Pod của ứng dụng backend.
metadata:
  name: ttnt-backend
spec:
  replicas: 1 # Số lượng bản sao (Pod) của ứng dụng backend sẽ được chạy.
  selector:
    matchLabels:
      app: ttnt-backend # Selector để Deployment biết Pod nào thuộc về nó.
  template:
    metadata:
      labels:
        app: ttnt-backend
    spec:
      containers:
        # Định nghĩa container chính cho ứng dụng backend.
        - name: ttnt-backend
          image: tuananh00/ttnt-backend:latest
          imagePullPolicy: Always # Luôn kéo ảnh mới nhất từ registry.
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-configmap # Tải tất cả các cặp key-value từ ConfigMap 'backend-configmap' vào biến môi trường.
          env:
            - name: DB_PASSWORD
              valueFrom: # Lấy mật khẩu từ Secret thay vì hardcode
                secretKeyRef:
                  name: mysql-secret # Tên của Secret chứa mật khẩu MySQL
                  key: ROOT_PASSWORD # Key chứa giá trị mật khẩu trong Secret
          resources:
            # Yêu cầu tài nguyên tối thiểu cho container.
            requests:
              cpu: "100m"
              # memory: "128Mi" # Ví dụ: yêu cầu 128 MiB RAM.
            # Giới hạn tài nguyên tối đa mà container có thể sử dụng.
            limits:
              cpu: "200m"
              # memory: "256Mi" # Ví dụ: giới hạn 256 MiB RAM.
          # Bổ sung Liveness Probe: Kiểm tra tiến trình Node.js có đang chạy không
          # Liveness Probe kiểm tra xem ứng dụng có còn sống hay không. Nếu probe thất bại, Kubernetes sẽ khởi động lại container.
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 3000
            initialDelaySeconds: 5 # Chờ 5 giây sau khi container khởi động mới bắt đầu kiểm tra
            periodSeconds: 10
          # Bổ sung Readiness Probe: Kiểm tra ứng dụng đã sẵn sàng nhận traffic chưa (đã kết nối DB)
          # Readiness Probe kiểm tra xem ứng dụng đã sẵn sàng nhận traffic hay chưa. Nếu probe thất bại, Pod sẽ không nhận traffic từ Service.
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 3000
            initialDelaySeconds: 5 # Chờ 5 giây sau khi container khởi động mới bắt đầu kiểm tra
            periodSeconds: 5