apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ttnt-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ttnt-backend # Trỏ đến Deployment của backend
  minReplicas: 1 # Số lượng Pod tối thiểu
  maxReplicas: 5 # Số lượng Pod tối đa
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Mục tiêu: duy trì CPU trung bình ở mức 50%