apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoneshop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tuananh04-hash/phoneshop-gitops.git'
    path: k8s
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true