apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoneshop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tuananh04-hash/phoneshop-gitops.git'
    path: phoneshop-chart # Trỏ đúng vào thư mục chứa Helm chart
    targetRevision: HEAD
    helm: # Khai báo rõ đây là một ứng dụng dùng Helm
      valueFiles:
        - values.yaml # Báo cho Argo CD nạp biến từ file này
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true