apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttnt-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttnt-frontend
  template:
    metadata:
      labels:
        app: ttnt-frontend
    spec:
      nodeName: node1 
      containers:
        - name: frontend
          image: 192.168.98.129:5000/ttnt-demo-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80