apiVersion: v1
kind: Service
metadata:
  name: ttnt-frontend
spec:
  type: ClusterIP # Thay đổi từ NodePort sang ClusterIP
  selector:
    app: ttnt-frontend
  ports:
    - port: 80
      targetPort: 80