# Số lượng Pod mặc định sẽ khởi tạo
replicaCount: 1

# Cấu hình Ingress: Đóng vai trò như "lễ tân" chia đường cho luồng mạng đi vào
ingress:
  enabled: true # Bật tính năng Ingress
  className: "nginx"
  # Annotations: "Ghi chú" đặc biệt để các controller khác (như cert-manager) đọc và xử lý
  annotations:
    # Chỉ thị cho cert-manager sử dụng ClusterIssuer tên là 'letsencrypt-prod' để cấp chứng chỉ
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: phoneshop.local # Tên miền truy cập
      paths:
        # Đường dẫn xác thực người dùng chuyển vào backend
        - path: /locgin
          pathType: Prefix
          serviceName: ttnt-backend
          servicePort: 3000
        # Các đường dẫn API khác chuyển vào backend
        - path: /api
          pathType: Prefix
          serviceName: ttnt-backend
          servicePort: 3000
        # Mặc định chuyển về giao diện Frontend
        - path: /
          pathType: Prefix
          serviceName: ttnt-frontend 
          servicePort: 80
  # Kích hoạt HTTPS (chứng chỉ bảo mật)
  tls:
   - secretName: phoneshop-tls-secret
     hosts:
       - phoneshop.local

# Tự động co giãn (thêm/bớt) số lượng Pod dựa trên tải CPU - Hiện đang tắt
autoscaling:
  enabled: false
  minReplicas: 1 # Số Pod tối thiểu
  maxReplicas: 5 # Số Pod tối đa
  targetCPUUtilizationPercentage: 80 # Ngưỡng CPU để bắt đầu tăng số lượng Pod

# -----------------------------------
# KHỐI CẤU HÌNH DÀNH RIÊNG CHO MYSQL
# -----------------------------------
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent # Chỉ tải image nếu máy node chưa có
  persistence:
    size: 1Gi # Xin K8s cấp 1GB ổ cứng vĩnh viễn (Persistent Volume) để lưu data
  rootPassword: "" # Để trống để tránh rò rỉ, sẽ truyền vào bằng tham số lúc gõ lệnh

# -----------------------------------
# KHỐI CẤU HÌNH DÀNH RIÊNG CHO BACKEND
# -----------------------------------
backend:
  name: ttnt-backend
  image:
    repository: tuananh00/ttnt-backend
    tag: latest
    pullPolicy: Always # Luôn tải image mới nhất khi khởi động Pod
  service:
    port: 3000 # Cổng nội bộ của ứng dụng Node.js
  resources:
    # Mức tài nguyên tối thiểu K8s phải cấp để Pod chạy
    requests:
      cpu: "100m"
      memory: "128Mi"
    # Mức tài nguyên tối đa Pod được phép ngốn (vượt mức này sẽ bị K8s giết)
    limits:
      cpu: "200m"
      memory: "256Mi"
  # Cấu hình "bác sĩ": K8s sẽ gõ cửa 2 đường dẫn này để biết Pod còn sống/sẵn sàng hay không
  livenessProbe:
    path: /healthz/live
  readinessProbe:
    path: /healthz/ready

# Phân quyền bảo mật RBAC (Role-Based Access Control)
rbac:
  create: true # Cho phép tự động tạo ServiceAccount và cấp quyền truy cập